### ISSUE TITLE
Why is version shown in Brackets 1.2.0?

### ISSUE THREAD

**Issue by PeterVermont** [brackets-beautify/brackets-beautify#226]
Why in the extensions menu in Brackets is it only showing the version from 8/11/2015?

https://github.com/brackets-beautify
![image](https://cloud.githubusercontent.com/assets/889233/19041072/aa08931c-8954-11e6-9963-d69faef91272.png)

I was looking for a replacement because of some issues, not realizing that I did there were updates available.

**Comment by Hirse** [comment]
Because transferring the ownership of an Extension in the Brackets Extension Registry is [apparently a big effort](https://github.com/adobe/brackets/issues/12464). 
Maybe you could try to give it a push, otherwise try to install the latest version (with updates) from the [Brackets npm registry](https://github.com/zaggino/brackets-npm-registry).

**Comment by vitorgalvao** [comment]
https://github.com/adobe/brackets-registry/pull/70 took a further step in fixing this.

**Comment by Hirse** [comment]
@vitorgalvao Yes, let's hope the change is deployed soon.

**Comment by Hirse** [comment]
The change is live and I have updated the version.
