### ISSUE TITLE
overrides command id

### ISSUE THREAD

**Issue by idphobia** [brackets-beautify/brackets-beautify#229]
> User Key Map for Beautify
> 
> Open the keymap.json with the menu entry Debug > Open User Key Map and add an overrides entry.
> For example:
> `
> {
>     "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
>     "overrides": {
>         "Ctrl-Alt-F": "bb.beautify.beautify"
>     }
> }
> `

it should be
me.drewh.jsbeautify ?

using "bb.beautify.beautify" is not working
ubuntu 14.0
brackets 14

**Comment by Hirse** [comment]
The Readme is for the versions 2.x which are unfortunately not available on the Brackets extension registry. Please update from url, clone the repository, or use the Brackets npm registry to get the latest version with the new command id.

**Comment by drewhamlett** [comment]
@Hirse Did we ever figure out how to update the extension?  I forget where that was left off at.

**Comment by Hirse** [comment]
@drewhamlett We are still stuck at the extension being owned by our org, which is not really supported by the Brackets Extension registry.
@ficristo seems to be aware of the [issue](https://github.com/adobe/brackets/issues/12464), but I am not sure what either of us can do.
In the meantime, I have uploaded it to npm, so that it can be installed using @zaggino's [Brackets npm Registry](https://github.com/zaggino/brackets-npm-registry) (although it doesn't use npm dependencies).

**Comment by Hirse** [comment]
@drewhamlett The Brackets team deployed a change that allows GitHub organizations to own extensions. I have updated the extension there.
