### ISSUE TITLE
[REQ] I would like to see python as code

### ISSUE THREAD

**Issue by schroef** [brackets-beautify/brackets-beautify#231]
Thanks for awesome script, works as a charm. Im wondering if its possible to add python or show a more detailed explination on how i can add python as a code tto this.

thanks!

**Comment by Hirse** [comment]
If you want to format Python code, there are two possibilities:
1. Provide a JavaScript library that formats Python code.
2. Use an external formatter, that is any shell/cmd command that takes a filename and returns the formatted code.
  See the readme for a [general guide](https://github.com/brackets-beautify/brackets-beautify#external-formatters) and the wiki for a [TypeScript example](https://github.com/brackets-beautify/brackets-beautify/wiki/External-Formatter:-TypeScript-Formatter-(tsfmt)).

**Comment by schroef** [comment]
I tried TypeScript but dont exactly understand how to add the python then.

**Comment by Hirse** [comment]
Can you give more information on what you tried?
What program / command to do use to format the Python code?

**Comment by schroef** [comment]
I believe i found a part of this one, but i dont know if it works how i think it would. https://github.com/beautify-web/js-beautify

There's is not really much info on how to implement external languages i guess. Or atleast not for a novice/beginner user

**Comment by Hirse** [comment]
[js-beautify](https://github.com/beautify-web/js-beautify) (which is the base of this extension) is a library to format JavaScript code. It is written in JavaScript, but also has a Python version (which still formats JavaScript).

If I understand your question correctly, you are looking for a way to format Python code inside Brackets (using this extension), right?
In order to use this extension for that purpose, you need to find (a library written in JavaScript) or more likely an external command line program that can provide that functionality.
Looking at your GitHub-profile, you have looked into [Python Tidy](https://pypi.python.org/pypi/PythonTidy). If we take that as an example, the command would be `python PythonTidy.py <filename>`.
Please make sure that this command (or the one you end up using) actually works when executed in the project directory.

This command then has to be added as [external formatter](https://github.com/brackets-beautify/brackets-beautify#external-formatters) to the `brackets.json`. The filename is getting attached by the extension.
```json
  {
      "bb.beautify.beautifiers": {
          "pythontidy": {
              "command": "python PythonTidy.py"
          }
      },
      "bb.beautify.languages": {
          "css": "css",
          "ejs": "html",
          "handlebars": "html",
          "html": "html",
          "javascript": "js",
          "json": "js",
          "less": "css",
          "php": "html",
          "scss": "css",
          "svg": "html",
          "vue": "html",
          "xml": "html",
          "python": "pythontidy"
      }
  }
```
