### ISSUE TITLE
Annoying space char

### ISSUE THREAD

**Issue by mhusein** [brackets-beautify/brackets-beautify#265]
* Brackets Version: Release 1.13 build 1.13.0-17696 (release 49d29a8bc) 
* Brackets Beautify Version: 2.5.2

before:
```php
<link href="<?php echo base_url()."bin";?>/css/bootstrap.min.css" rel="stylesheet">
```

after:
```php
<link href="<?php echo base_url()." bin ";?>/css/bootstrap.min.css" rel="stylesheet">
```

it kept adding space char before and after word -> bin \
final result --> `/%20bin%20/css/bootstrap.min.css`

**Comment by Hirse** [comment]
You are seeing this issue because PHP is only supported as HTML. If you look at your snippet as HTML, the double quotes surrounding `"bin"` make it look like it is terminating the `href` value which causes the spaces to be inserted.

Support for this case is unlikely to be added to our formatter, but your specific case can be solved by using single quotes for the PHP string:
```php
<link href="<?php echo base_url().'bin';?>/css/bootstrap.min.css" rel="stylesheet">
```
