### ISSUE TITLE
Error SAVE BEAUTIFY in ASP

### ISSUE THREAD

**Issue by marmmc** [brackets-beautify/brackets-beautify#267]
Hello, Developer...

I'ts cool extension to brackets, BRACKETS-BEAUTIFY.
Last update, not function in language programmer .ASP.

ERROR:
If question, tag, code:
1) normal is `SET strRS("id") = "" THEM`
2) apply brackets-beautfiy, she is code separated ID: `SET strRS(" id ") = "" THEM`

In the last update, important solved question, code.
No more, tankyou.

Goodbye.

**Comment by Hirse** [comment]
ASP is not supported by itself. I am assuming you are using it in HTML.

Could you please share a larger snippet of your code? Please include the whole tag (`< ... >`).

I have a suspicion that this is a similar issue to the one described in https://github.com/brackets-beautify/brackets-beautify/issues/265: If you use double quotes (`"`) inside an HTML attribute, the formatter will add spaces because it cannot distinguish between the quotes ending the attribute and those meant for a different language inside the attribute value.
Try using single quotes (`'`) for ASP where possible.

**Comment by marmmc** [comment]
hello mr hirse.

i am submited print, view image: CODE in ASP
![image](https://user-images.githubusercontent.com/19541991/47014353-6a74d380-d120-11e8-8727-e01ca23d327a.png)

my code save BEAUTIFY, she always insert space in code, but not could, generates error in server, not recognize code;

yout have solutions to error????

tankyou returned

**Comment by Hirse** [comment]
I am not sure which exact space you are referring to, but if it the one in line 5, you can try the following:
```ASP
<option value="<%=strEstados('UF')%>"
```
Basically, don't use double quotes inside HTML attributes.

Please keep in mind that __ASP is not one of the supported languages__.

Finally, in the future please don't use screenshots. Add text for the expected and actual formatting inside code blocks.

**Comment by bitwiseman** [comment]
@marmmc @Hirse 
The next version of beautify (v1.9.0 - currently in beta) has better support for templating.
It will work for both
`<option value="<%=strEstados('UF')%>">` and `<option value="<%=strEstados("UF")%>">`.

**Comment by bitwiseman** [comment]
@marmmc
Please try with v2.7.0. Should be fixed now.
