### ISSUE TITLE
No line break on beautify for XML element if tag name is 'code'

### ISSUE THREAD

**Issue by ErnestoHoro** [brackets-beautify/brackets-beautify#303]
**Details about your environment:**
* Brackets Version: Release 1.14 build 1.14.2-17770 (release-1.14.2 f71f00acc) 
* Brackets Beautify Version: 2.12.0 (and older versions I have not tracked)
* OS Version: Windows 10 Pro 1909

# Input Code

```xml
<Hello>World</Hello><Code>1</Code>
<Hello>World</Hello><NotCode>1</NotCode>
```

# Result Current

```xml
<Hello>World</Hello><Code>1</Code>
<Hello>World</Hello>
<NotCode>1</NotCode>
```

# Result Expected

```xml
<Hello>World</Hello>
<Code>1</Code>
<Hello>World</Hello>
<NotCode>1</NotCode>
```

# Notes

* XMLs already formatted as in 'Result Expected' are not altered
* behavior seems to be case insensitive (COde, Code, code, ...)

Regards :)

**Comment by Hirse** [comment]
This seems to be caused by re-using the HTML-mode to format XML.
In HTML some tags are considered "inline" (vs. "block"). In those inline tags, extra whitespace (such as new lines) actually change the output so the formatter does not want to modify them.

I removed this distinction for XML since it should treat all elements equally there.

Unfortunately, it seems Brackets removed the option to update extensions (most likely related to their upcoming end of support for Brackets as a whole), so you might need to install the update from file here:
https://github.com/brackets-beautify/brackets-beautify/releases/tag/v2.13.0
